CREATE SCHEMA  IF NOT EXISTS connections;
CREATE SCHEMA  IF NOT EXISTS dictionary;
CREATE SCHEMA  IF NOT EXISTS history;
CREATE SCHEMA  IF NOT EXISTS humanresource;
CREATE SCHEMA  IF NOT EXISTS projects;